# Generated by Django 6.1.1 on 2026-09-13 07:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('birth_date', models.DateField(verbose_name='Birth Date')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=10)),
                ('current_academic_level', models.CharField(choices=[('P.1', 'Primary 1'), ('P.2', 'Primary 2'), ('P.3', 'Primary 3'), ('P.4', 'Primary 4'), ('P.5', 'Primary 5'), ('P.6', 'Primary 6'), ('S.1', 'Secondary 1'), ('S.2', 'Secondary 2'), ('S.3', 'Secondary 3'), ('S.4', 'Secondary 4'), ('S.5', 'Secondary 5')], max_length=100, verbose_name='Current Academic Level')),
                ('enrolment_status', models.CharField(choices=[('Active', 'Active'), ('dismissed', 'Dismissed'), ('transferred', 'Transferred'), ('graduated', 'Graduated')], default='Active', max_length=100, verbose_name='Enrolment Status')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='students/photos')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
