# Generated by Django 6.1.1 on 2026-09-14 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_management', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='current_academic_level',
            new_name='academic_level',
        ),
        migrations.RemoveField(
            model_name='student',
            name='enrolment_status',
        ),
        migrations.AddField(
            model_name='student',
            name='enrollment_status',
            field=models.CharField(choices=[('Active', 'Active'), ('dismissed', 'Dismissed'), ('transferred', 'Transferred'), ('graduated', 'Graduated')], default='Active', max_length=100, verbose_name='Enrollment Status'),
        ),
    ]
